baseURL = "https://pages.bigtear.com"
languageCode = "zh-cn"
title = "BigTear 的记录"
theme = "github-style"
#googleAnalytics = "UA-107784973-4"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。<br /><br />背景使用了 <a href="https://www.pexels.com/zh-cn/" target="_blank">Pexels</a> 上 <a href="https://www.pexels.com/zh-cn/@minan1398" target="_blank">Min An</a> 拍摄的<a href="https://www.pexels.com/zh-cn/photo/1454794/" target="_blank">图片</a>。'
pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
  author = "Alexander Phillips"
  github = "BigTear"
  description = "己所不欲，勿施于人。"
  twitter = "none"
  email = "admin@bigtear.com"
  utterances = "BigTear/hugo.git"
  rss = true
  location = "China"
  lastmod = true
  enableGitalk = true

[params.gitalk]
  clientID = "905e6647dc2f58d151df" # Your client ID
  clientSecret = "9d99babed34a673dfe98489b34ebba8da6d18695" # Your client secret
  repo = "hugo"
  owner = "bigtear"
  admin = "bigtear"
  id = "location.pathname"
  labels = "gitalk"
  perPage = 15
  pagerDirection = "last"
  createIssueManually = true
  distractionFreeMode = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[[params.links]]
  title = "Github"
  href = "https://github.com/bigtear"